### PR TITLE
Use RavenHydroFramework from official GitHub source

### LINKED ISSUE #23: Support Raven 3.8
### Checklist

- [ ] Remove RavenHydroFramework source files within code base and link to https://github.com/CSHS-CWRA/RavenHydroFramework as a submodule
- [ ] Expose Pybind11 version string from RavenHydroFramework code base
- [ ] Update internal metadata to reflect new changes

### PR DESCRIPTION
**Pull request by Zeitsperre**
### Pull Request Checklist:
- [x] This PR addresses an already opened issue (for bug fixes / features)
    - This PR fixes #23 
- [x] Tests for the changes have been added (for bug fixes / features)
  - [ ] (If applicable) Documentation has been added / updated (for bug fixes / features)
- [x] CHANGES.rst has been updated (with summary of main changes)

### What kind of change does this PR introduce?

* Points the `RavenHydroFramework` source files to the official GitHub project
* Updates the version of Raven to 3.8
* Updates the CMake configuration to use git-based clones
* Both the version number and the description are now dynamic (using `hatch-fancy-pypi-readme` and `setuptools_scm`).
* Support has been extended to Python3.12
* Now uses `scikit-build-core`>=0.8.0

### Does this PR introduce a breaking change?

Yes. The copied source files have been removed. There is more integration with the actual project source files.

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@huard

I've spent way too much time on this today. Here's what I've figured out:
- Running the `cmake` commands directly on the upstream codebase `RavenHydroFramework` works fine (so long as the `STANDALONE` and `COMPILE_EXE` flags are there).
- When compiling things here, it's clear that the functions defined in `RavenMain.cpp` are not being passed to other files. `ExitGracefully()` is only found in a `.cpp` file and not in a header, and this file isn't included in a bunch of `.cpp` files that make references to that function.
- Unsurprisingly, if you could and paste the following into the top-matter of all `.cpp` files, the `ExitGracefully()` error disappears:
> ```c++
>   #ifdef STANDALONE
>       #include "GracefulEndStandalone.h"
>   #elif BMI_LIBRARY
>       #include "GracefulEndBMI.h"
>   #endif 
>   ```

I've been trying to read up on ways of passing the objects from `RavenMain.cpp` to all other files, but I have no idea if that's even what we want. I get the impression that the problem has to do with scopes (perhaps vanilla `cmake` is a lot less strict about ensuring that files are included explicitly?).

@analytophile am I on the right track here?

**Comment by huard** [comment]
@Zeitsperre 

I suspect this is a false lead. Your installation setup works on master, and the code compiles fine using the original cmakelist. I believe there is a quirk related to the source files location introduced in the git fetch mechanism that we need to identify. I'll take a look later this week.

**Review by huard — COMMENTED** [review]
I suggest to use the same target names and env variables as in the original cmakelist to reduce confusion. 

Targets:
- libraven
- ravenbmi
- Raven

```
option(COMPILE_LIB "If ON, will create a dynamic lib file (default: OFF)" OFF)
option(COMPILE_EXE "If ON, will create a executable file (default: ON)" ON)
option(PYTHON, "If ON, will create a share library for python (default: OFF)" OFF)
```

**Comment by Zeitsperre** [comment]
Seems to be working! The only issue I can see is that the model reports a non-fatal error:
```
 3.8.0 w/ netCDF
============== Early Gracefully Exit ==============
Error Statement: Version check
Error Code: 7
---------------------------------------------------
```

@huard any idea what that could be?

**Comment by Zeitsperre** [comment]
Needed to set the fetch-depth for setuptools_scm. See: https://github.com/pypa/setuptools_scm/issues/414

**Review by huard — APPROVED** [review]

**Pull request merged**
